// AI-generated (Claude)
// Minimal libdivecomputer <version.h> stub. The upstream header is generated by
// libdc's build system and is absent from a plain header checkout. The planner
// core only needs the version macros/declaration to exist; no libdc function is
// actually called on the planning path.
#ifndef SUBSURFACE_WASM_DC_VERSION_STUB
#define SUBSURFACE_WASM_DC_VERSION_STUB

#define DC_VERSION "0.0.0-wasm-stub"
#define DC_VERSION_MAJOR 0
#define DC_VERSION_MINOR 0
#define DC_VERSION_MICRO 0
#define DC_VERSION_CHECK(major, minor, micro) (0)

#ifdef __cplusplus
extern "C" {
#endif
const char *dc_version(char *string);
#ifdef __cplusplus
}
#endif

#endif
